(load-file "~/.emacs.d/config/load-path-config.el")
(load-file "~/.emacs.d/config/utils.el")

(load-file "~/.emacs.d/config/basic-config.el")
(load-file "~/.emacs.d/config/zencoding-mode-config.el")

(load-file "~/.emacs.d/config/migemo-config.el")
(load-file "~/.emacs.d/config/auto-complete-config.el")
(load-file "~/.emacs.d/config/skk-config.el")
(load-file "~/.emacs.d/config/server-config.el")
(load-file "~/.emacs.d/config/window-config.el")
(load-file "~/.emacs.d/config/anything-config.el")
(load-file "~/.emacs.d/config/yasnippet-config.el")
;; (load-file "~/.emacs.d/config/auto-revert-mode-config.el")
(load-file "~/.emacs.d/config/carbon-config.el")
(load-file "~/.emacs.d/config/perl-config.el")
(load-file "~/.emacs.d/config/html-config.el")
(load-file "~/.emacs.d/config/css-config.el")
(load-file "~/.emacs.d/config/flymake-config.el") ;; XXXXXXXX
;; (load-file "~/.emacs.d/site-lisp/flymake-growl.el")
(load-file "~/.emacs.d/config/js-config.el")
(load-file "~/.emacs.d/config/as-config.el")
;; (load-file "~/.emacs.d/config/outputz-config.el")
(load-file "~/.emacs.d/config/ruby-config.el")
(load-file "~/.emacs.d/config/ruby-refe-config.el")
(load-file "~/.emacs.d/config/shell-config.el")
(load-file "~/.emacs.d/config/smartchr-config.el")
(load-file "~/.emacs.d/config/tex-config.el")
(load-file "~/.emacs.d/config/yaml-config.el")
;; (load-file "~/.emacs.d/config/rsense-config.el")
(load-file "~/.emacs.d/config/auto-save-buffers-config.el")
(load-file "~/.emacs.d/config/dictionary-config.el")
(load-file "~/.emacs.d/config/git-config.el")
(load-file "~/.emacs.d/config/override-config.el")


(message "hi")
